# Generated by Django 5.0.2 on 2024-03-03 22:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.CharField(default='18:00', max_length=5)),
                ('numMyside', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('numOtherside', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('ratio', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amountMyside', models.IntegerField(default=0)),
                ('amountOtherside', models.IntegerField(default=0)),
                ('charge', models.IntegerField(default=0)),
                ('remarks', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
