# Generated by Django 5.0.2 on 2025-05-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0005_historymodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
